### ISSUE TITLE
unable to get it to work

### ISSUE THREAD

**Issue by mkvpr** [martinjanas/IdleMinerAutomator#1]
I made a copy and added webhook. I connects to discord but will not send commands.

**Comment by martinjanas** [comment]
You need to edit the HWND variable to find the window, it should match the title of window.

from HWND hwnd = FindWindowA(NULL, "#hello - Discord"); to HWND hwnd = FindWindowA(NULL, "general - Discord");

**Comment by mkvpr** [comment]
I had a channel named "hello" for it. So now I made a channel "general" and changed the title in the code but still no commands are coming through.

**Comment by mkvpr** [comment]
Is there somewhere else we can chat, that way I'm not making a bunch of
comments on your github?

**Comment by martinjanas** [comment]
MartiN#2418 on Discord
